<?xml version="1.0" encoding="UTF-8"?><testrun name="Test (2)" project="eduit-webapp" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="testing.Test" time="0.0">
    <testcase name="testFecha" classname="testing.Test" time="0.0">
      <failure>junit.framework.AssertionFailedError&#13;
	at junit.framework.Assert.fail(Assert.java:55)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:22)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:31)&#13;
	at junit.framework.TestCase.assertTrue(TestCase.java:200)&#13;
	at testing.Test.testFecha(Test.java:31)&#13;
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testDocumento" classname="testing.Test" time="0.0"/>
  </testsuite>
</testrun>
